//
//  LocalizableKeys.swift
//  Spica
//
//  Created by Adrian Baumgart on 16.07.20.
//

import Foundation

enum LocalizableKeys: String {
	case HOME = "HOME"
	case NOTIFICATIONS = "NOTIFICATIONS"
	case ACCOUNT = "ACCOUNT"
	case SETTINGS = "SETTINGS"
	
	case REPLY_SINGULAR = "REPLY_SINGULAR"
	case REPLY_PLURAL = "REPLY_PLURAL"
	
	case LOADING_ACTION = "LOADING_ACTION"
	
	case POST_NOUN = "POST_NOUN"
	case NEWPOST_PLACEHOLDER = "NEWPOST_PLACEHOLDER"
	
	case IMAGE = "Image"
	
	case SELECT_ANOTHER_IMAGE = "SELECT_ANOTHER_IMAGE"
	
	case REMOVE = "REMOVE"
	
	case CANCEL = "Cancel"
	
	case POST_SENT = "POST_SENT"
	
	case REPLY_ACTION = "REPLY_ACTION"
	
	case FOLLOWER_SINGULAR = "FOLLOWER_SINGULAR"
	case FOLLOWER_PLURAL = "FOLLOWER_PLURAL"
	
	case RUBY_SINGULAR = "RUBY_SINGULAR"
	
	case RUBY_PLURAL = "RUBY_PLURAL"
	
	case FOLLOW_ACTION = "FOLLOW_ACTION"
	
	case FOLLOWING_ACTION = "FOLLOWING_ACTION"
	
	case FOLLOWS_YOU = "FOLLOWS_YOU"
	
	case EDIT_PROFILE = "EDIT_PROFILE"
	case NAME = "NAME"
	case NICKNAME = "NICKNAME"
	case ABOUT = "ABOUT"
	
	case SAVED_ACTION = "SAVED_ACTION"
	
	case COPIED_ACTION = "COPIED_ACTION"
	case DELETED_ACTION = "DELETED_ACTION"
	
	case DELETE_POST = "DELETE_POST"
	case DELETE_CONFIRMATION = "DELETE_CONFIRMATION"
	case DELETE_ACTION = "DELETE_ACTION"
	
	case VERSION = "VERSION"
	case BUILD = "BUILD"
	
	case GO_TO_PROFILE = "GO_TO_PROFILE"
	case SIGN_OUT = "SIGN_OUT"
	
	case PRIVACY_POLICY = "PRIVACY_POLICY"
	case TERMS_OF_SERVICE = "TERMS_OF_SERVICE"
	case WEBSITE = "WEBSITE"
	
	case USED_LIBRARIES = "USED_LIBRARIES"
	case CREDITS = "CREDITS"
	
	case OTHER = "OTHER"
	
	case SPICA_COPYRIGHT = "SPICA_COPYRIGHT"
	
}
